# Site settings
title: email charter
email: ms+emailcharter@michsch.de
description: "emailcharter.de ist eine freie deutsche Ãœbersetzung von emailcharter.org."
baseurl: ""
url: "http://emailcharter.de"
twitter_username: michsch
github_username:  michsch

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: expanded

gems:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

destination: public
source: src

exclude: ['node_modules']
